/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "#0a0a0a",
        "on-primary": "#ffffff",
        canvas: "#ffffff",
        surface: "#f7f8fa",
        "surface-soft": "#f2f3f5",
        hairline: "#e5e7eb",
        "hairline-soft": "#eaecf0",
        ink: "#0a0a0a",
        charcoal: "#222222",
        slate: "#45515e",
        steel: "#5f5f5f",
        stone: "#8e8e93",
        muted: "#a8aab2",
        "success-bg": "#e8ffea",
        "success-text": "#1ba673",
        "brand-coral": "#ff5530",
        "brand-magenta": "#ea5ec1",
        "brand-blue": "#1456f0",
        "brand-blue-mid": "#3b82f6",
        "brand-blue-deep": "#1d4ed8",
        "brand-cyan": "#3daeff",
        "brand-blue-200": "#bfdbfe",
        "brand-purple": "#a855f7",
        "footer-bg": "#0a0a0a",
      },
      fontFamily: {
        sans: ["'DM Sans'", "Inter", "'Helvetica Neue'", "Helvetica", "Arial", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        xxl: "20px",
        xxxl: "24px",
        hero: "32px",
        full: "9999px",
      },
      fontSize: {
        "hero-display": ["80px", { lineHeight: "1.10", letterSpacing: "-2px", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.10", letterSpacing: "-1.5px", fontWeight: "600" }],
        "heading-lg": ["40px", { lineHeight: "1.20", letterSpacing: "-1px", fontWeight: "600" }],
        "heading-md": ["32px", { lineHeight: "1.25", letterSpacing: "-0.5px", fontWeight: "600" }],
        "heading-sm": ["24px", { lineHeight: "1.30", fontWeight: "600" }],
        "card-title": ["20px", { lineHeight: "1.40", fontWeight: "600" }],
        subtitle: ["18px", { lineHeight: "1.50", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.50" }],
        "body-sm": ["14px", { lineHeight: "1.50" }],
        caption: ["13px", { lineHeight: "1.70" }],
        micro: ["12px", { lineHeight: "1.50" }],
      },
      boxShadow: {
        card: "0 1px 2px 0 rgba(0,0,0,0.04)",
        "card-hover": "0 4px 6px 0 rgba(0,0,0,0.08)",
        atmospheric: "0 0 22px 0 rgba(0,0,0,0.08)",
        modal: "0 12px 16px -4px rgba(36,36,36,0.08)",
      },
    },
  },
  plugins: [],
};
